### PR TITLE
Add Shuffle Button to Comics Grid

### PR DESCRIPTION
**Pull request by scottblechman**
## Feature Description
Adds an option to view a random comic directly from the comics grid.

## Changelist
- Third button added to floating buttons row (see attached screenshots)
    - On iOS, button is centered horizontally in row
    - On iPadOS, button is grouped with other floating buttons
- Button press opens comic pager already shuffled
- Floating buttons preview updated with test response

## Testing Steps
- Open XKCDY to the comics grid, confirming shuffle button is visible matching the above specs. 
- If not already available, add 2 or more comics to the Favorites tab.
- Press the shuffle button in the All tab, confirming that a random comic is displayed.
- Press the shuffle button in the Favorites tab, confirming that only a random favorite comic is displayed.

## E2E Criteria
- Settings and search buttons work as intended when pressed
- All three buttons work and display as intended in both portrait and landscape mode
- Pressing on a comic from the comics grid works as intended, before and after shuffling from the grid
- All actions from the comic overlay work as intended for the target comic
- Returning to the comics grid from a random comic behaves the same as from a non-random comic

## Issues Noticed During Testing
- Rapidly switching between the All and Favorites tab can crash the application. Reproducible in stable version without the above changes.

## Screenshots
Shuffle Button - iPhone 8 Plus

Shuffle Button - iPad Pro (12 9-inch) (4th generation)

### CODE REVIEW

**Comment by codetheweb** [comment]
Looks pretty good, thank you for the contributions! Having the button in the center looks decent.

My only request would be that the shuffle logic is moved to the button handler itself (changing `store.currentComicId`). This would remove some of the complexity, like `shuffleButtonPressed`. `self.filteredCollection().randomElement()?.id` should do the trick.

> Rapidly switching between the All and Favorites tab can crash the application. Reproducible in stable version without the above changes.

I was unable to reproduce this, what device and OS are you using?

**Comment by scottblechman** [comment]
I'm on an iPhone 8 Plus running 13.6.1, but I also saw it on the iPhone 11 sim with 13.6. What I had to do was time the tab switch before the images were fetched, but had to give it a few tries. On the sim I got this output when it crashed:
`Fatal error: No ObservableObject of type Store found. A View.environmentObject(_:) for Store may be missing as an ancestor of this view.: file SwiftUI, line 0`

I'm amending the older commits with the GPG signature, it'll be included with the shuffle logic update and a couple of style fixes SwiftLint caught.

**Comment by codetheweb** [comment]
Can you please merge the latest from master into your branch and see if you can still reproduce the issue?

I'm still working on a few bugs, but hopefully should be able to look at this more thoroughly later today.

**Comment by scottblechman** [comment]
I can test the changes later today, I'll add a new comment with what I find out.

**Comment by codetheweb** [comment]
I just fixed one bug I noticed and updated from master, if you wanna take one last look to make sure everything's good before I merge it in that'd be great.

Can I give you a shout out in the update release notes? 😛

**Comment by scottblechman** [comment]
Sure! Thanks for the shout out, glad that I was able to help 🙂

I can't make the tab issue happen anymore, so bug-wise it looks good to me.

**Comment by codetheweb** [comment]
Finally released in 1.0.3 after spending the required amount of time in review purgatory.

**Pull request merged**
